language: cpp  # Укажите, что используете C++

# Укажите компилятор, который будете использовать
compiler:
  - gcc - clang

# Команды, которые будут выполняться перед тестами
before_script:
  - echo "Проверка наличия файла test_travis.txt"

# Команды тестирования
script:
  - if [ ! -f test_travis.txt ]; then echo "Файл test_travis.txt отсутствует!" && exit 1; fi
  - wc -l test_travis.txt  # Подсчет строк в файле
